### ISSUE TITLE
How this algorithm performs for people who are not in the training set?

### ISSUE THREAD

**Issue by tfwang08** [Zhangjinso/PINet_PG#1]
Hello，thanks for your great work. I am not very familiar with pose transfer. I want to ask how this algorithm performs for people who are not in the training set?

**Comment by Zhangjinso** [comment]
Hi，pose transfer is an image generation task conditioned on a target pose and a source person. We train the neural network to let it learn how to utilize the information of the person image and the target pose to generate a new image with the same person but in the target pose. Like other condition image generation tasks (e.g., image inpainting),  the unkown person in the testing set can be interpolated in the latent space using the knowledge of the training data.

**Comment by tfwang08** [comment]
Thank you for your reply, it helped me a lot.
