### ISSUE TITLE
how to prepare parsing data?

### ISSUE THREAD

**Issue by linyh1998** [Zhangjinso/PINet_PG#2]
Hi!Imprssive work product. I want to test on my own data.So how do I prepare parsing data?

**Comment by Zhangjinso** [comment]
Hi, sorry for the delay. If you want to test your own data, you need prepare your parsing data followed by https://github.com/Engineering-Course/CIHP_PGN. Note that we re-organize the label of human parsing map. Please check our test data to confirm the organization.

**Comment by linyh1998** [comment]
Hi.Sorry I didnt find your test data.So how do you re-organize the label of human parsing map?

**Comment by Zhangjinso** [comment]
The test parsing data is in https://pan.baidu.com/s/1Ic8sIY-eYhGnIoZdDlhgxA (fetch code:abcd). You can decoded followed by https://github.com/Engineering-Course/CIHP_PGN/blob/master/utils/utils.py to see the organization of it.

**Comment by linyh1998** [comment]
thanks
